### PR TITLE
Dates defaulting when not empty

### PR DESCRIPTION
**Pull request by orangemug**
Dates were defaulting when they weren't empty. Turns out you can't use `_.isEmpty` with dates, this fixes this issue by adding an additional check.

### CODE REVIEW

**Comment by eleith** [comment]
can you write one unit test to demonstrate the desired behavior? otherwise, looks good.

**Comment by orangemug** [comment]
Sure are you ok for the test to be in this format https://github.com/codemix/oriento/tree/master/test/bugs, labeled by github issue id? (I think it's quite nice)

**Comment by orangemug** [comment]
@eleith I added a commit to another branch off of master (called `bug/failing-date-test`) so I could prove to myself it was failing previously. Then I merged that branch into `feature/date-fix` which is now passing correctly.

**Comment by eleith** [comment]
this looks good. i agree, do you want to create a bugs folder and rename your test 13-default-date.js or something like that?

**Comment by orangemug** [comment]
@eleith refactored as per comments

**Pull request merged**
