### PR TITLE
Added <https://wzrd.in/> example.

### PR DESCRIPTION
**Pull request by orangemug**

### CODE REVIEW

**Comment by orangemug** [comment]
@eleith also would you be up for removing https://github.com/eleith/schemajs/blob/master/lib/schema.js#L101 and putting it in a new file?

I was thinking in `./middleware.js`, then we can include it with the following

    var schemaMiddleware = require("schemajs/middleware");

This way we don't include it in the browser bundle?

**Comment by eleith** [comment]
1) i like the suggestion to use browserify
2) i support the suggestion to move middleware out to its own file
3) i would prefer promote offline tools like browserify, webpack or r.js through grunt, gulp, brocolli or general CLI tools instead of wzrd.in

**Comment by orangemug** [comment]
@eleith so the reason for using wzrd.in (the browserify service) instead of other CLI tools (browserify, webpack or r.js) is that it allows anyone to get built file easily. I've found working with other projects that a common ask is for a built file you can just include with a `<script>` tag. The other alternative is to keep a built files in the repo in a `/dist` directory, but they get out of sync really easily and make it hard to just accept a PR via the UI (basically too much extra work)

Saying all of the above my pull request doesn't really address that :). How about I add a download link to the top of the README

    [built version](https://wzrd.in/standalone/schemajs@latest)

Then add instructions for browserify via the CLI into the README and remove the example entirely.

Thoughts?

**Comment by eleith** [comment]
i agree that build files in a repo tend to get out of sync quickly.

one way around that is to write a script that does the build upon execution and check that into the repo. then users can run it (or have a git hook that runs it)

with that said, simplying pointing users to a link does that same without having to do an `npm install --dev-dependencies` and running a build script.

**Comment by eleith** [comment]
adding a build script can come in another future PR. this PR is good enough for now and can be removed later (especially since example files will eventually go stale...)

**Pull request merged**
